# Generated by Django 4.1.7 on 2023-03-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='deccription',
            new_name='description',
        ),
    ]
